enableRobotsTXT: true
description: # used as fall back if not page description/summary is found
title: # set the site title here, seo.title page/site config is an override

# adds newer content older page's related content
related:
  includeNewer: true
  threshold: 0
  toLower: true
  indices:
  - name: keywords
    weight: 100
  - name: categories
    weight: 50
  - name: tags
    weight: 80

