seo:
  generate:
    title: true
    meta: true
    twitter: true
    og: true
    jsonld:
      article: true
      breadcrumbs: true
  title_tag:
    separator: "|"
    home_text: "" # prepend this text on home page
  siteName: # site title override (for og/twitter)
  ogArticleTypes: [post, posts, blog, news, article, articles, event, events, course, courses]
  jsonldArticleTypes: [article, articles]
  jsonldNewsArticleTypes: [news, updates]
  jsonldBlogPostingTypes: [post, posts, blog]
  # page or site
  image: # set default here, page override can be set. 
  private: false # set here or per page to modify robots meta, remove sitemap, robots and rss listing for page(s)
    
  # page only
  # title: # page title override for title tag, og and twitter
  # description: # override other descriptions for seo
  # canonical: # add page ref to override .Permalink for canonical


