# (site.Title used by seo for title tag and others)
# (site.Social.twitter (with no @))

seo:
  # site only
  generate:
    title: true
    meta: true
    twitter: true
    og: true
    jsonld:
      article: true
      breadcrumbs: true
  titleSeparator: "|"
  siteName: # site title override (for og/twitter)
  ogArticleTypes: [post, posts, blog, news, article, articles, event, events]
  jsonldArticleTypes: [article, articles, event, events]
  jsonldNewsArticleTypes: [news]
  jsonldBlogPostingTypes: [post, posts, blog]
  # page or site
  image: # set default here, page override can be set. 
  private: false # set here or per page to modify robots meta, remove sitemap, robots and rss listing for page(s)
    
  # page only
  # title: # page title override for title tag, og and twitter
  # description: # override other descriptions for seo
  # canonical: # add page ref to override .Permalink for canonical


# page params
# params:
#   description: #precedence over summary
#   summary: 
# .publishDate #precedence over .date
# .date
# .lasmod


