# (site.Title used by seo for title tag and others)
# (site.Social.twitter (with no @))

description: # used as fallback for seo 

seo:
  # site only
  generate:
    title: true
    meta: true
    twitter: true
    og: true
    jsonld:
      article: true
      breadcrumbs: true
  titleSeparator: "|"
  siteName: # site title override (for og/twitter)
  enableFollow: true # enable index,follow meta if private != true and production env

  articleTypes: [post, posts, blog, news]
  eventTypes: [article]

  # page or site
  image: # set default here, page override can be set.

  # page only
  # private: true 
  # title: # page title override for title tag, og and twitter
  # description: # override other descriptions for seo
  # canonical: # add page ref to override .Permalink for canonical


# page params
# params:
#   description: #precedence over summary
#   summary: 
# .publishDate #precedence over .date
# .date
# .lasmod



# .type blog, news > article
# .type article > event 
# use config???

# translations > .lang

